# Generated by Django 3.2 on 2021-09-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=38, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('manga_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=38, unique=True)),
                ('author', models.CharField(max_length=38)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('brief', models.TextField()),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ymdb.manga')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Manga',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ymdb.manga')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ymdb.tag')),
            ],
            options={
                'unique_together': {('tag', 'manga')},
            },
        ),
        migrations.CreateModel(
            name='Gallery_Manga',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ymdb.gallery')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ymdb.manga')),
            ],
            options={
                'unique_together': {('gallery', 'manga')},
            },
        ),
    ]
