# Generated by Django 3.2 on 2021-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
