# Generated by Django 3.2 on 2021-09-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0002_alter_manga_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(to='ymdb.Tag'),
        ),
        migrations.DeleteModel(
            name='Tag_Manga',
        ),
    ]
