# Generated by Django 3.2 on 2021-09-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0003_auto_20210919_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='mangas',
            field=models.ManyToManyField(to='ymdb.Manga'),
        ),
        migrations.DeleteModel(
            name='Gallery_Manga',
        ),
    ]
