# Generated by Django 3.2 on 2021-09-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0006_alter_manga_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='rate',
            new_name='rating',
        ),
    ]
