# Generated by Django 3.2 on 2021-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymdb', '0007_rename_rate_manga_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
